import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Header from "../components/header/header"

const grotesk = localFont({
	src: [
		{
			path: "./fonts/gratogrotesk-light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
})

export const metadata: Metadata = {
	title: "MRNET",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${grotesk.className} antialiased`}>
				<div className='max-w-[1368px] ml-auto mr-auto mb-0 mt-0 pr-2 pl-2'>
					<Header />

					{children}
				</div>
			</body>
		</html>
	)
}
