import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Header from "../components/header/header"
import Footer from "../components/footer/footer"
import Container from "../components/container/container"

const grotesk = localFont({
	src: [
		{
			path: "./fonts/gratogrotesk-light.woff",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-regular.woff",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-medium.woff",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/gratogrotesk-bold.woff",
			weight: "700",
			style: "normal",
		},
	],
})

export const metadata: Metadata = {
	title: "MRNET",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={`${grotesk.className} antialiased`}>
				<Container>
					<Header />
				</Container>
				{children}

				<Footer />
			</body>
		</html>
	)
}
